export type UserRole = 'admin' | 'house_manager' | 'supervisor' | 'nurse' | 'caregiver' | 'billing';

export const rolePermissions = {
  admin: {
    canViewAuditLogs: true,
    canManageUsers: true,
    canManageClients: true,
    canManageCaregivers: true,
    canManageCarePlans: true,
    canManageSchedule: true,
    canViewAllReports: true,
    canManageBilling: true,
    canManageMedical: true,
    canApproveTimesheets: true,
  },
  house_manager: {
    canViewAuditLogs: false,
    canManageUsers: false,
    canManageClients: true,
    canManageCaregivers: true,
    canManageCarePlans: false,
    canManageSchedule: true,
    canViewAllReports: true,
    canManageBilling: false,
    canManageMedical: false,
    canApproveTimesheets: true,
  },
  supervisor: {
    canViewAuditLogs: false,
    canManageUsers: false,
    canManageClients: true,
    canManageCaregivers: true,
    canManageCarePlans: true,
    canManageSchedule: true,
    canViewAllReports: true,
    canManageBilling: false,
    canManageMedical: false,
    canApproveTimesheets: true,
  },
  nurse: {
    canViewAuditLogs: false,
    canManageUsers: false,
    canManageClients: false,
    canManageCaregivers: false,
    canManageCarePlans: true,
    canManageSchedule: false,
    canViewAllReports: false,
    canManageBilling: false,
    canManageMedical: true,
    canApproveTimesheets: false,
  },
  caregiver: {
    canViewAuditLogs: false,
    canManageUsers: false,
    canManageClients: false,
    canManageCaregivers: false,
    canManageCarePlans: false,
    canManageSchedule: false,
    canViewAllReports: false,
    canManageBilling: false,
    canManageMedical: false,
    canApproveTimesheets: false,
  },
  billing: {
    canViewAuditLogs: false,
    canManageUsers: false,
    canManageClients: false,
    canManageCaregivers: false,
    canManageCarePlans: false,
    canManageSchedule: false,
    canViewAllReports: false,
    canManageBilling: true,
    canManageMedical: false,
    canApproveTimesheets: false,
  },
};

export function hasPermission(role: UserRole, permission: keyof typeof rolePermissions.admin): boolean {
  return rolePermissions[role]?.[permission] ?? false;
}
